### ISSUE TITLE
What components are needed to run this code on a new computer

### ISSUE THREAD

**Issue by hualuoyu** [harfang3d/dogfight-sandbox-hg2#103]
Dear developer,
      When I download the code in one new computer, follow the readme.md to execute the code, the code can not run, will suddenly abort, as shown in the photo:
![QQ20241223-100646](https://github.com/user-attachments/assets/f94727ce-40db-4c03-a3a9-570de39aa47e)
      Depending on the configuration.json file, OpenGL may be required to run this code, but does it  need any other components? Please help me.

**Comment by Angar0Os** [comment]
Hello @hualuoyu ,

I performed a fresh installation of the project from scratch to understand where your issue might be coming from.
Like you, I followed the README and successfully completed the installation.
I have this configuration.json file, which I am attaching as a screenshot for you.

I have several questions for you:

 -  Which version of Python are you using?
 - Did you encounter any issues during the installation of the requirements?
 - Do you have the "assets-compiled" folder as shown in the screenshot below after the compilation?

Thank you for your feedback.

![image](https://github.com/user-attachments/assets/41c75ddb-751d-4d13-a963-c487a386a478)
![image](https://github.com/user-attachments/assets/bc27cd9a-a3a4-479a-a39d-67a49f45191c)

**Comment by zjz5250** [comment]
> Hello @hualuoyu ,
> 
> I performed a fresh installation of the project from scratch to understand where your issue might be coming from. Like you, I followed the README and successfully completed the installation. I have this configuration.json file, which I am attaching as a screenshot for you.
> 
> I have several questions for you:
> 
> * Which version of Python are you using?
> * Did you encounter any issues during the installation of the requirements?
> * Do you have the "assets-compiled" folder as shown in the screenshot below after the compilation?
> 
> Thank you for your feedback.
> 
> ![image](https://private-user-images.githubusercontent.com/122360705/398385742-41c75ddb-751d-4d13-a963-c487a386a478.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMTMzNTcsIm5iZiI6MTczNTIxMzA1NywicGF0aCI6Ii8xMjIzNjA3MDUvMzk4Mzg1NzQyLTQxYzc1ZGRiLTc1MWQtNGQxMy1hOTYzLWM0ODdhMzg2YTQ3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQxMTM3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YmEwY2Y1MTZlN2NlOTUyZjU5YjFiYjNhNDliMGQxZjcwMjQxOTcxNjZkNjM3OGRlNWIzMjU4NmY0NWUzNmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9n6WUFn8TL8dXOLc6cvgAvIx0MSxcQNhCDSwXQZiNMQ) ![image](https://private-user-images.githubusercontent.com/122360705/398385600-bc27cd9a-a3a4-479a-a39d-67a49f45191c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMTMzNTcsIm5iZiI6MTczNTIxMzA1NywicGF0aCI6Ii8xMjIzNjA3MDUvMzk4Mzg1NjAwLWJjMjdjZDlhLWEzYTQtNDc5YS1hMzlkLTY3YTQ5ZjQ1MTkxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQxMTM3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDY0NWE3Nzc1ODRhMDRjMjc2MThiYWE1MTc5NzJjMzNhMzJlYmRjZGI4Mzc3YWExNTk4YmVjNWViZGQ1NTIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XPP3jrsF1-D5uG__hrKr9dvfoMAeP6MzW11Sp_NnoHA)
========================================================================
Hi， I try to run the project，but encounter some problems  as follows：
（1）I encountered the following problems when installing the project under Windows 11
         the code version is v1.3.1 released，and using python3.9.13，harfang-3.2.5-py3-none-win_amd64.whl。
        After I complete the installation，I execute the command “ python main.py” in the source folder。but encounter the error：
       “ImportError: DLL load failed while importing harfang”
        Am I missing some steps？
（2）I encountered the following problems when installing projects under ubuntu
         the code version is v1.3.1 released，and using python3.9.13，harfang-3.2.5-cp32-abi3-linux_x86_64.whl。
         After I complete the installation，I execute the command “ python main.py” in the source folder。but encounter the error：“No module named _sqlite3”

**Comment by zjz5250** [comment]
@Angar0Os 
Hi, I am very interested in this project, thank you for your work and sharing.
According to the readme document, after downloading the official release versionv 1.3.1, I can directly execute the start.bat file，right？but when I execute the star.bat，the problem occurred： “ImportError: DLL load failed while importing harfang”

**Comment by Angar0Os** [comment]
Hello,

It seems that you are missing some DLLs for the project.

 - Have you installed the project requirements using the 0-install-requirements.bat file?
 - Did you encounter any errors?

If so, try the following:

    - Upgrade pip with the following command: python.exe -m pip install --upgrade pip

If that did not work:

    - Upgrade your Python version to python=3.10.0
    - Upgrade pip using the same command as earlier
    - Install the requirements
    - Run start.bat
    
If you did not encounter any issues, check that python.exe is included in your environment variables.
It seems that the issue is the same on Linux. Let me know if the problem persists.

**Comment by zjz5250** [comment]
Thank you for your reply.
I use the code  is official released v1.3.1，and there has no  0-install-requirements.bat file.
As you suggested, should use the code  downloaded  form  repository, is it?
I will try  it  again.
thanks very much

**Comment by Angar0Os** [comment]
Yes, you should use the code from the repository.
We will update the release to fix this issue.
I will keep you informed in this thread when the release is available.

**Comment by zjz5250** [comment]
This time，I install the project as follows, but the problem occured again。
（1）I use the code download from the repository
（2）The python version is 3.9.13
（3）I  installed the project requirements using the 0-install-requirements.bat file without errors。
when I execute “python main.py”，the problem occurred： “ImportError: DLL load failed while importing harfang”
And，I will try it with  python3.10.

**Comment by zjz5250** [comment]
![python310](https://github.com/user-attachments/assets/0bebf700-1e93-4f81-bf8a-284cf95e7acb)
It still do not work。
that's strange

**Comment by zjz5250** [comment]
Maybe，it is because my win11 has some problems。
when I execute import harfang using python3.10  in another pc，it is ok.
I will completely install the project in  the new pc.
then  I  will feedback the result

**Comment by zjz5250** [comment]
I  did it.
use python3.10，the code downloaded from the repository，and install the project requirements using the 0-install-requirements.bat file。The project can run finally！
Thank you very much！

**Comment by zjz5250** [comment]
wow, ubuntu20.04 can also be success!
(1)python3.9,
(2) The code is downloaded from the repository
(3) complete the installation as follows:
     cd souce
     python -m pip install -r source/requirements.txt
     python -m pip install -r Agent/requirements.txt

**Comment by zjz5250** [comment]
![network mode](https://github.com/user-attachments/assets/4d98307c-7ab8-4d53-85a8-9043c2889cfd)
Why is there no ip and port number in network mode  in ubuntu20.04, while  the ip and port number can be seen in the top left corner in win11

**Comment by zjz5250** [comment]
![ip port](https://github.com/user-attachments/assets/d8ae83e7-1883-4e5f-b549-844aa7fc294d)
It is the IP and port in win11

**Comment by astrofra** [comment]
> Why is there no ip and port number in network mode in ubuntu20.04, while the ip and port number can be seen in the top left corner in win11

Hi.
This seems to be a display-related problem. We are currently investigating it on a Ubuntu machine. I'll keep you posted.
Thanks again for your interest in the Dogfight Sandbox.

**Comment by astrofra** [comment]
@zjz5250 Hi.
It seems there is a bug on Linux when calculating the position of the HUD within the main window area.
I found a quick workaround : 

Modify the window size in the `config.json` file, as below : 
```json
{
    "Resolution": [1600, 800],
	"FullScreen": false,
	"OpenGL": true,
	"VR": false, 
	"AntiAliasing": 4,
	"ShadowMap": true
}
```

You should obtain this:
 
![Screenshot from 2024-12-30 11-05-36](https://github.com/user-attachments/assets/d2e49366-d7cf-4325-bbae-3491514edbe2)

**Comment by Angar0Os** [comment]
Hello @zjz5250.
I just updated all text positions so the HUD can display properly.
Let me know if you have other issues.

**Comment by zjz5250** [comment]
Yes，I have updated my code，and the problem has been solved。
Thanks a lot！




JunZ翟
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "harfang3d/dogfight-sandbox-hg2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月30日(星期一) 晚上10:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [harfang3d/dogfight-sandbox-hg2] What components are needed to run this code on a new computer (Issue #103)





 
Hello @zjz5250.
 I just updated all text positions so the HUD can display properly.
 Let me know if you have other issues.

**Comment by Angar0Os** [comment]
Thank you for your feedback and your interest in this project.
