### ISSUE TITLE
help

### ISSUE THREAD

**Issue by muzhizhao** [harfang3d/dogfight-sandbox-hg2#11]
What does the position and rotation of the aircraft refer to?
I can currently obtain the quantitative information of the speed of the aircraft, but cannot obtain the speed vector information of the aircraft. How can I obtain it?

**Comment by ErkMkd** [comment]
Hi!
If you run the dogfight directly: the `Aircraft.v_move` vector is probably what you need.
If you use the network server: the `get_planestate(plane_id)["move_vector"]` parameter is the speed vector.
The vector is in m.s-1

I hope I've helped you !

**Comment by muzhizhao** [comment]
Thank you very much for your answer. I don't know much about the knowledge of aircraft dynamics that appears in the code. Do you have any recommended reference books or references?

**Comment by burakkurtt** [comment]
@muzhizhao you can check out "Aircraft Control and Simulation (3rd Ed.) Dynamics, Controls Design, and Autonomous Systems"  from Steven & Lewis for aircraft dynamics, simulation and control.

**Comment by muzhizhao** [comment]
Thank you very much！
