### ISSUE TITLE
is there linux support

### ISSUE THREAD

**Issue by kadirnar** [harfang3d/dogfight-sandbox-hg2#2]
I want to run this library on ubuntu. Is there Ubuntu support?

Error Message:
```
from .harfang import *
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by astrofra** [comment]
Hi!

You are experiencing troubles to run the HARFANG wheel on your Linux (Ubuntu) distribution.
HARFANG is built on the Python 3 ABI, making it able to run on any Python 3 major version, from 3.2 to 3.9 (or even 3.10).
However, Linux is still looking for a specific .so name.

Could you please copy paste the entire error message, starting from `Traceback (most recent call last):` ? 
What version of Python 3 are you running ?

**Comment by kadirnar** [comment]
Ide: Pycharm
Version: Python 3.8
OS: Ubuntu 20.04

I have the file /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0. But there is no version 3.6

**Comment by astrofra** [comment]
Yeah. For some reason, the HARFANG wheel is tied to a specific .so.
But it will run perfectly on your Python 3.8.

Could you please try this: 

```
sudo ln -s libpython3.8.so.1.0 libpython3.6m.so.1.0
```

Then you will probably need to install GLFW:

```
sudo apt install libglfw3
```

**Comment by kadirnar** [comment]
I have installed libpython3.6m.so.1.0. but it gives the same error. I solved this error by moving libpython3.6m.so.1.0 to x86_64-linux-gnu folder. Thank you for helping me resolve this error.

I got a different error regarding assets.exe. I will open that error in different issues.

**Comment by astrofra** [comment]
OK.
Thanks for your feedback!
