### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by muzhizhao** [harfang3d/dogfight-sandbox-hg2#24]
I'm sorry to bother you， but I currently want to use this dogfighting software as a simulation environment to verify the reliability of some flight algorithms. How should I control the aircraft through flight data and what data do I need to control？

**Comment by ErkMkd** [comment]
Hi ! You can use the network mode to control aircraft. You can find client side samples code here:  
https://github.com/harfang3d/dogfight-sandbox-hg2/tree/main/network_client_example  
And an overview in the ReadMe.  
Don't hesitate to ask me if you encounter any difficulties !

**Comment by muzhizhao** [comment]
I have successfully operated according to your readme file, and I want to ask you What are the specific operations in the sample file（client_sample）? What should I do if I need to operate the aircraft through network mode, such as controlling the linear acceleration of flight

**Comment by ErkMkd** [comment]
You can set the plane thrust level, but not directly set the linear acceleration:
https://github.com/harfang3d/dogfight-sandbox-hg2/blob/main/network_client_example/client_sample.py#L43  

But if you want a full control of physics, you can set the "custom physics mode":  
https://github.com/harfang3d/dogfight-sandbox-hg2/blob/main/network_client_example/client_sample_custom_physics.py#L32  
...And set your own plane matrix:  
https://github.com/harfang3d/dogfight-sandbox-hg2/blob/main/network_client_example/client_sample_custom_physics.py#L63
