### ISSUE TITLE
Question about rendering with client sample

### ISSUE THREAD

**Issue by mrwangyou** [harfang3d/dogfight-sandbox-hg2#25]
Hi! 

First of all, thank you for your great effort in the field of dogfight simulations and build this wonderful platform. 

I have problems using "Network mode" with client_*.py code. I made a screen record, but the video is too big to be uploaded on Github, so I upload it on OneDrive. You could download it in the link below.

[https://1drv.ms/u/s!AjYxuXuKCgSEvjGBt1HkUVXPusP-?e=cRpGYp](https://1drv.ms/u/s!AjYxuXuKCgSEvjGBt1HkUVXPusP-?e=cRpGYp)

In this trial, the rendering couldn't be played correctly while the program and even the sound works well. When I tried to run client_sample.py, the rendering will play after the program is finished. So did the client_sample_missile_custom_phisics.py. 

Besides, just a small suggestion. The IP and port displayed in the top-left corner of the screen would be hidden if the sandbox windows was in different size, along with health, bullets, etc. 

I'm using Windows 10 Home edition, 
CPU: Intel Core i7 11700
RAM: DDR4 32GBytes
GPU: NVIDIA GeForce RTX 3070

**Comment by ErkMkd** [comment]
Ok, it seems that you use an old version of the package:  
![image](https://user-images.githubusercontent.com/11889393/183389841-87ced268-22eb-4e77-b5b8-a5bf62c6a339.png)  
You can download newest version here:  
https://github.com/harfang3d/dogfight-sandbox-hg2/releases  
Get the "dogfight-sandbox-hg2.rar" file.  
Tell me if you find the same bug with this version.
Sincerely,
Eric

**Comment by mrwangyou** [comment]
Hi Eric,

Thank you for your reply. I tried the newest version. I found that `client_sample_missile_custom_physics.py` could work correctly, but there's still some error with `client_sample.py`.
