### ISSUE TITLE
Question about customizing instances

### ISSUE THREAD

**Issue by mrwangyou** [harfang3d/dogfight-sandbox-hg2#30]
Hi

I'm doing research about dogfighting between planes. I want to design some simple instances, such as a flare countermeasure, and add those to dogfight 2 environments. I wonder whether there is any manual of guidance. Thank you!

**Comment by ErkMkd** [comment]
Hi, sorry for the late response.
Unfortunately, there is no easy way to add such a system. I'll think about it though, if I can make a tutorial. 
Sincerely
Eric

**Comment by mrwangyou** [comment]
@ErkMkd 

Thank you for your reply, and your effort to air combat simulation.
