### ISSUE TITLE
Help！

### ISSUE THREAD

**Issue by muzhizhao** [harfang3d/dogfight-sandbox-hg2#31]
Hello, I am currently conducting scientific research and development based on your software. I would like to ask what algorithm is the flight combat strategy of the enemy aircraft in this software based on?

**Comment by ErkMkd** [comment]
Hi ! It's a very basic algorithm:
In outline:  
-AI points the plane at the enemy  
-Fires machine gun when the enemy is close enough, in a 15° cone  
-Shoot the missile when it is locked, with a delay so as not to shoot all the missiles at once.  
-Regain altitude if the plane is too low,  
-Go to land if there are not enough minutions or if the plane is too damaged.  

You can find the loop here:
https://github.com/harfang3d/dogfight-sandbox-hg2/blob/main/source/MachineDevice.py#L1993

Sincerely,
Eric

**Comment by muzhizhao** [comment]
Thank you for your sincere answer, this solved a lot of my difficulties!

**Comment by muzhizhao** [comment]
Hello, I want to change the game to a RL env！Which part should I modify?
Is it ok to just run the program from the source if I don't need the visualization window (the ability to run in renderless mode)？

**Comment by ErkMkd** [comment]
Hi !
You just have to activate the renderless mode. Hit "R" during the simulator to switch Render/Renderless mode.
I just have made a fix for delta_t of the Renderless mode. Wait a couple of minutes until the update is ok.

**Comment by muzhizhao** [comment]
Thank you for your reply, in addition, I have a new question while reading the source code and I hope to get your answer.
I would like to know how the trajectory of the aircraft is updated, I can't find the source code corresponding to it

**Comment by ErkMkd** [comment]
Here:
https://github.com/harfang3d/dogfight-sandbox-hg2/blob/main/source/Machines.py#L1903

**Comment by muzhizhao** [comment]
I am trying to run the enemy aircraft separately from the environment, how can I do this to get the next position information and print it just by updating the dynamics of the enemy aircraft?

**Comment by ErkMkd** [comment]
Hi !
You just have to get the plane you want to control in planes list:
planes_list = df.get_planes_list()
plane_id = planes_list[...] # Index of the plane you need

you can update the dogfight in lient update mode:
df.set_client_update_mode(True)

Then, call the update when you need:
df.update_scene()

Finally, get the plane informations:
plane_state = df.get_plane_state(plane_id)

Hope this helps you ?

**Comment by ErkMkd** [comment]
Wait, i probably have a solution for you.
I have a generic function here:
https://github.com/harfang3d/dogfight-sandbox-hg2/blob/main/source/Physics.py#L112

I can expose it in network mode.

**Comment by muzhizhao** [comment]
Thank you for your patience and explanation!

**Comment by ErkMkd** [comment]
I pushed the new network mode function: "compute_next_timestep_physics" 
You can see a usecase at "client_sample.py".

Hope this can do what you need !

**Comment by muzhizhao** [comment]
Thank you very much for your efforts, I am trying to update the position of the aircraft just by updating the update_physics function (https://github.com/harfang3d/dogfight-sandbox-hg2/blob/main/source/Physics.py#L112), i.e. not by running the dogfight software.
For example, the initial position of the aircraft is known, as well as other physics parameters, and the update_physics function is used to get the move_vector, which calculates the next position
