### ISSUE TITLE
About citation

### ISSUE THREAD

**Issue by mrwangyou** [harfang3d/dogfight-sandbox-hg2#34]
Hi! I wonder whether there is any paper about Dogfight 2 so that I could cite if I make use of this sandbox in my research? Or I can just cite this Github page? Thank you

**Comment by mrwangyou** [comment]
@astrofra Thank you for your reply. That's very kind of you to help me list all the related papers here. I think I expressed the wrong thought and sorry for that. I'd like to ask if you and your team published a paper which introduce Dogfight so that I can cite Dogfight in my work. Thank you again for your help.

**Comment by astrofra** [comment]
@mrwangyou, indeed, sorry I misunderstood your question.
There is not publication from us, so far. But there is an upcoming paper that includes a contribution from @ErkMkd (who implemented most of the Sandbox). I will keep you posted as soon as the paper is online.

**Comment by mrwangyou** [comment]
> @mrwangyou, indeed, sorry I misunderstood your question. There is not publication from us, so far. But there is an upcoming paper that includes a contribution from @ErkMkd (who implemented most of the Sandbox). I will keep you posted as soon as the paper is online.

Thank you for your reply. I'm looking forward to reading the paper. 

I'm also working on air combat simulations these days. I build an air combat platform with Dogfight and JSBSim, which is another flight dynamics model. Dogfight is utilized to simulate the situation when the plane is confronted with a missile and trying to escape the attack. The project is still be completing and I'm trying to build an air combat simulation platform for intelligent algorithm researchers. If you want to get some informations, you could have a look at the [Github Page](https://github.com/mrwangyou/DBRL).
