### ISSUE TITLE
A fatal error occurred when I tried to open dogfight

### ISSUE THREAD

**Issue by muzhizhao** [harfang3d/dogfight-sandbox-hg2#36]
The python environment I'm using is the anaconda virtual environment, and the following error occurs when I open dogfight：
If I open it through the source main file it shows:
Harfang 3.2.4 for CPython 3.2+ on windows-x64 (build 2002087e407e25dcd76a597f4b180bb6c82a5332 Sep 19 2022 14:31:06)
See https://www.harfang3d.com/license for licensing terms
Compiling assets...
  0%|          | 0/100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "D:\Users\14290\Desktop\dogfight-sandbox-hg2-main\source\main.py", line 66, in <module>
    dc.run_command("../bin/assetc/assetc assets -api GL -quiet -progress")
  File "D:\Users\14290\Desktop\dogfight-sandbox-hg2-main\source\data_converter.py", line 79, in run_command
    for line in execute_com(exe):
  File "D:\Users\14290\Desktop\dogfight-sandbox-hg2-main\source\data_converter.py", line 74, in execute_com
    p = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "D:\ANACONDA\envs\harfang2\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\ANACONDA\envs\harfang2\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the specified file。
  0%|          | 0/100 [00:00<?, ?it/s]

 If I open it through the start.bat it shows:
d:\Users\14290\Desktop\dogfight-sandbox-hg2-main>cd source

d:\Users\14290\Desktop\dogfight-sandbox-hg2-main\source>..\bin\python\python.exe main.py
'..\bin\python\python.exe' Not an internal or external command, not a runnable program
or a batch file

d:\Users\14290\Desktop\dogfight-sandbox-hg2-main\source>pause

**Comment by ErkMkd** [comment]
Hi !
You can download the latest release version: [](https://github.com/harfang3d/dogfight-sandbox-hg2/releases/tag/v1.0.14)
Which contains all binaries.
Tell me if it works or not.

**Comment by astrofra** [comment]
Hi :)
@muzhizhao your problem here is that the binaries are missing.
The dogfight needs 3 binaries to run : 
  - python.exe
  - the harfang wheel
  - assetc.exe (the asset compiler)
  
  It is not a good practice to include binaries into a GIT repository, so the best thing is to do as @ErkMkd suggested, get the binaries from the release version and copy them into your cloned folder (see the [`bin\` folder](https://github.com/harfang3d/dogfight-sandbox-hg2/tree/main/bin), it contains the information you are looking at)

**Comment by muzhizhao** [comment]
WOW!Thank you very much, I successfully started dogfight with your patient guidance!

**Comment by astrofra** [comment]
> WOW!Thank you very much, I successfully started dogfight with your patient guidance!

Thanks for the feedback.
Are you running the Dogfight on Anaconda ?

**Comment by muzhizhao** [comment]
> > WOW!Thank you very much, I successfully started dogfight with your patient guidance!
> 
> Thanks for the feedback. Are you running the Dogfight on Anaconda ?

Yes!
