### ISSUE TITLE
About citations

### ISSUE THREAD

**Issue by muzhizhao** [harfang3d/dogfight-sandbox-hg2#38]
Hi！
      I had some problems reading your citation "HARFANG3D DOG-FIGHT SANDBOX: A REINFORCEMENT LEARNING RESEARCH PLATFORM FOR THE CUSTOMIZED CONTROL TASKS OF FIGHTER AIRCRAFTS". I contacted you by email and did not get a reply. 
      Due to a lack of expertise and experience, we could not achieve the results shown in your paper. I would like to ask if I can get the source code and algorithm for the experimental part of the article
       l am looking forward to your reply as soon as possible!

**Comment by ErkMkd** [comment]
Hi !
Sorry for my late response.
My contribution to this article covers the physics and rendering part (part 2). The algorithm used for reinforcement learning is the work of the Turkish team (part 3). I can guide you through the native Dogfight algorithms, but it is not AI.
For the algorithm you are interested in, you can contact directly Muhammed Murat Özbek, Süleyman Yıldırım or Muhammet Aksoy.
If you need help to use your own Reinforcement Learning code, don't hesitate to ask me !
sincerely,
Eric

**Comment by ErkMkd** [comment]
I send you an email with Murat linked in Cc ;)

**Comment by muzhizhao** [comment]
Thank you very much for your prompt reply! I would like to reproduce the experimental part of your paper and use my own reinforcement learning code for further research afterward. In the meantime, I have contacted Muhammed Murat Özbek and if I can get access to your source code, I can always contact you if I have any questions about the physics and rendering part!

**Comment by ErkMkd** [comment]
Murat use his algorithm through the Network mode of Dogfight. This way he did not have to enter the simulator code directly.
I developed the Network mode according to his needs. If you need other special features, I can add them to the Network Mode, if possible.

**Comment by muzhizhao** [comment]
I am also going to use my algorithm through the network mode of Dogfight. 
I have read and studied your example in network mode and it works sufficiently, and I am learning how to combine it with reinforcement learning algorithms in network mode.
I am very interested in your work and am ready to reproduce it!
