### ISSUE TITLE
About multiple dogfight-sandboxes

### ISSUE THREAD

**Issue by muzhizhao** [harfang3d/dogfight-sandbox-hg2#51]
Hi,
 I am working on a reinforcement learning project using the Harfang platform and I would like to ask how to enable multiple dogfight-sandboxes in network mode to achieve parallel training?

**Comment by muraatozbek** [comment]
I commented from
 https://github.com/harfang3d/dogfight-sandbox-hg2/blob/15b01ba9bd33a5ed2b08fdba8c6368d86c9ab833/source/main.py#L19
to  **line 28** and after added this code.

`port = input('Port : ')
nwport = int(port)
netws.dogfight_network_port = nwport`

when you run the code it will ask port number give different port numbers and in each starting different game you can run parallel training.

**Comment by cjmdd** [comment]
> I commented from
> 
> https://github.com/harfang3d/dogfight-sandbox-hg2/blob/15b01ba9bd33a5ed2b08fdba8c6368d86c9ab833/source/main.py#L19
> 
> to **line 28** and after added this code.
> 
> `port = input('Port : ')` `nwport = int(port)` `netws.dogfight_network_port = nwport`
> 
> when you run the code it will ask port number give different port numbers and in each starting different game you can run parallel training.

Hello, I have some questions. Can you help me? 
Question one: the dogfight cannot obtain states of missiles launched by planes when we test client_sample_missile_custom_physics.py. There are some errors: "Nonetype" object has no attribute 'decode'.
Question two: the dogfight are unable to reset airplanes to sky in the reset function including reset_machine(), reset_machine_matrix() and rearm_machine() after they are shot down or crashed. It is unfriendly to RL training.
These questions confused me, thanks.
