### ISSUE TITLE
 How can I make it work without graphical display on docker or server, just like StarCraft

### ISSUE THREAD

**Issue by cjmdd** [harfang3d/dogfight-sandbox-hg2#62]
Because I want to train them on the server, but both the local machine and the server are ubuntu18.04, so I created a container of ubuntu20.04 with the docker, and installed harfang and doglight in it. But because the docker and the server can not be displayed graphically, the error occurred in running main.py: window_init error.  And, it cannot work when I set "OpenGL": true in config.json. Therefore, how can I make it work without graphical display, just like StarCraft

**Comment by zrc0622** [comment]
Hello! I noticed your previous discussion about running software on a server without graphical display. I'm quite intrigued by this topic, as I'm also working in a similar context. Could you please share more detailed steps and methods on how to successfully run software in an environment without a display?   I would greatly appreciate it if you could share some key insights and steps with me.

**Comment by 8acemak1rkey** [comment]
I meet the same problem,do you have any ideas?
