### ISSUE TITLE
The Socket Client Receive the Nonetype Date

### ISSUE THREAD

**Issue by yannwennliu** [harfang3d/dogfight-sandbox-hg2#75]
I'm getting an error when using your latest version of network_client_example.
The terminal printout shows that my client's socket received a new error while decoding. The client's socket received the None which cannot be decoded.I would like to know the reason for this problem. Thank for your helping.

**Comment by cjmdd** [comment]
Can you solve the problem? we cannot obtain states of missiles launched by aircraft when running df.get_missiles_state()
