### ISSUE TITLE
where can i make it not show logs?

### ISSUE THREAD

**Issue by TUY3** [harfang3d/dogfight-sandbox-hg2#8]
![image](https://user-images.githubusercontent.com/59690192/164373719-34f7e3a8-e464-4aa0-9bc1-b02c3c262323.png)

**Comment by ErkMkd** [comment]
To set the lowest log level, you can add the following lines 
`hg.SetLogDetailed(False)` (already defined in line 64 of main.py)
`hg.SetLogLevel(hg.LL_Normal)`

**Comment by astrofra** [comment]
In addition to what Eric suggested, you can redirect the log output to a text file, by editing this file: https://github.com/harfang3d/dogfight-sandbox-hg2/blob/main/start.bat

as follows:

```bat
cd source
..\bin\python\python.exe main.py > log.txt
pause
```

Please note that it's not always a good idea to mute the log of an application :)

**Comment by TUY3** [comment]
> In addition to what Eric suggested, you can redirect the log output to a text file, by editing this file: https://github.com/harfang3d/dogfight-sandbox-hg2/blob/main/start.bat
> 
> as follows:
> 
> ```batchfile
> cd source
> ..\bin\python\python.exe main.py > log.txt
> pause
> ```
> 
> Please note that it's not always a good idea to mute the log of an application :)

Thanks!!! I will look at the log sometimes!
